### ISSUE TITLE
account is not defined

### ISSUE THREAD

**Issue by pyskell** [ConnextProject/indra#1]
Having an issue starting up a Hub using the instructions in the Readme. This is on Debian 9.

Followed the Readme steps to the letter. Ganache is running fine at the same time.

```
#truffle migrate --reset --network development
ReferenceError: account is not defined
    at Object.<anonymous> (/root/Indra/truffle.js:19:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Function.Config.load (/usr/lib/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:254:1)
    at Function.Config.detect (/usr/lib/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:243:1)
    at Object.run (/usr/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/commands/migrate.js:35:1)
    at Command.run (/usr/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/command.js:101:1)
    at Object.<anonymous> (/usr/lib/node_modules/truffle/build/webpack:/packages/truffle-core/cli.js:22:1)
    at __webpack_require__ (/usr/lib/node_modules/truffle/build/webpack:/webpack/bootstrap b393854eec71a4a28b46:19:1)
    at /usr/lib/node_modules/truffle/build/webpack:/webpack/bootstrap b393854eec71a4a28b46:65:1
    at Object.<anonymous> (/usr/lib/node_modules/truffle/build/cli.bundled.js:71:10)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

Seems that despite trying to use the development configuration the lack of a defined account in `truffle.js` is causing the error:

```
    ropsten: {
      host: "127.0.0.1",
      port: 8545,
      network_id: "3",
      from: account,
      gas: 4700000
    },
```

Removing the `from: account,` line fixes the error.

**Comment by hthillman** [comment]
Good catch @pyskell. We'll take out the `from: account,` line--there were a few last minute changes and that got left in
