### ISSUE TITLE
Attempting to uninstall an app that isn't installed

### ISSUE THREAD

**Issue by bohendo** [ConnextProject/indra#270]
**Describe the bug**
Client throws timeout error, hub logs:
```
[Nest] 66   - 08/29/2019, 10:24 AM   [ListenerService] protocolMessageEvent event fired from xpub6FJdkaiZyL6JasDivts8SuH1GvkkRsCBNysetFytppZYjjAJoajAVT1oZ6kXwdCgsBozNzsyossbz7mMDsni3u2H1g7tq4fj8jKWj9HZq9x, data: {"protocol":"uninstall","processID":"2fe2eb00-ca47-11e9-ba73-731b0c699039","params":{"initiatorXpub":"xpub6FJdkaiZyL6JasDivts8SuH1GvkkRsCBNysetFytppZYjjAJoajAVT1oZ6kXwdCgsBozNzsyossbz7mMDsni3u2H1g7tq4fj8jKWj9HZq9x","responderXpub":"xpub6E3tjd9js7QMrBtYo7f157D7MwauL6MWdLzKekFaRBb3bvaQnUPjHKJcdNhiqSjhmwa6TcTjV1wSDTgvz52To2ZjhGMiQFbYie2N2LZpNx6","multisigAddress":"0x826167d2aBd124c15eD433D4476b44478154C802","appIdentityHash":"0x4fb8c06cc35862c28a66b5f8f6745c74d0c734d3e6f21275e1273fd62ea3703f"},"toXpub":"xpub6E3tjd9js7QMrBtYo7f157D7MwauL6MWdLzKekFaRBb3bvaQnUPjHKJcdNhiqSjhmwa6TcTjV1wSDTgvz52To2ZjhGMiQFbYie2N2LZpNx6","customData":{"signature":{"recoveryParam":0,"r":"0x9f92eb60a5c1b3f9e5558656b1ea64db6967d6a95ac092a6652db6c2145151aa","s":"0x7a26a92e3098115fa1a6add274be1f833a5dace32d994052e24cb3ba0143b151","v":27}},"seq":1}
[Nest] 66   - 08/29/2019, 10:24 AM   [ListenerService] protocolMessageEvent event fired from xpub6FJdkaiZyL6JasDivts8SuH1GvkkRsCBNysetFytppZYjjAJoajAVT1oZ6kXwdCgsBozNzsyossbz7mMDsni3u2H1g7tq4fj8jKWj9HZq9x, data: {"processID":"2fc06ee0-ca47-11e9-ba73-731b0c699039","params":{"initialState":{"threshold":{"_hex":"0x0"},"tokenAddress":"0x0000000000000000000000000000000000000000","recipient":"0xBab56B0B061ECd8Fa3eDec1e0E75171A6aCd49c5","multisig":"0x826167d2aBd124c15eD433D4476b44478154C802"},"initiatorXpub":"xpub6FJdkaiZyL6JasDivts8SuH1GvkkRsCBNysetFytppZYjjAJoajAVT1oZ6kXwdCgsBozNzsyossbz7mMDsni3u2H1g7tq4fj8jKWj9HZq9x","responderXpub":"xpub6E3tjd9js7QMrBtYo7f157D7MwauL6MWdLzKekFaRBb3bvaQnUPjHKJcdNhiqSjhmwa6TcTjV1wSDTgvz52To2ZjhGMiQFbYie2N2LZpNx6","multisigAddress":"0x826167d2aBd124c15eD433D4476b44478154C802","initiatorBalanceDecrement":{"_hex":"0x00"},"responderBalanceDecrement":{"_hex":"0x00"},"participants":["0x55334540B0D390A21cB618961F851c6b0ff099cc","0xe156F03eeE6bf2f7A6e48fCD7E26181Df69D888F"],"appInterface":{"addr":"0x345cA3e014Aaf5dcA488057592ee47305D9B3e10","stateEncoding":"\n  tuple(\n    address recipient,\n    address multisig,\n    uint256 threshold,\n    address tokenAddress\n  )\n"},"defaultTimeout":1008,"outcomeType":"SINGLE_ASSET_TWO_PARTY_COIN_TRANSFER","initiatorDepositTokenAddress":"0x0000000000000000000000000000000000000000","responderDepositTokenAddress":"0x0000000000000000000000000000000000000000","disableLimit":true},"protocol":"install","toXpub":"xpub6E3tjd9js7QMrBtYo7f157D7MwauL6MWdLzKekFaRBb3bvaQnUPjHKJcdNhiqSjhmwa6TcTjV1wSDTgvz52To2ZjhGMiQFbYie2N2LZpNx6","customData":{"signature":{"recoveryParam":0,"r":"0x9ff88b6bd348696e8b508e045eb5d4cb88b6a00242c4a255c2fcfdb8eb086a94","s":"0x0a189732a34d54296aa66a97e302dca75eda65b1a01110bed59aeff252573d20","v":27}},"seq":1}
(node:66) UnhandledPromiseRejectionWarning: Error: Attempted to edit an appInstance that does not exist: identity hash = 0x4fb8c06cc35862c28a66b5f8f6745c74d0c734d3e6f21275e1273fd62ea3703f
    at StateChannel.getAppInstance (/root/node_modules/@counterfactual/node/src/models/state-channel.ts:113:13)
    at proposeStateTransition$1 (/root/node_modules/@counterfactual/node/src/protocol/uninstall.ts:122:8)
    at proposeStateTransition (/root/node_modules/@counterfactual/node/src/protocol/uninstall.ts:71:58)
    at Generator.next (<anonymous>)
    at resume (/root/node_modules/@counterfactual/node/dist/index.js:52:44)
    at /root/node_modules/@counterfactual/node/dist/index.js:51:121
    at new Promise (<anonymous>)
    at Object.i.(anonymous function) [as next] (/root/node_modules/@counterfactual/node/dist/index.js:51:63)
    at InstructionExecutor.runProtocol (/root/node_modules/@counterfactual/node/src/machine/instruction-executor.ts:148:33)
    at InstructionExecutor.runProtocolWithMessage (/root/node_modules/@counterfactual/node/src/machine/instruction-executor.ts:99:17)
```

**To Reproduce**
1. `git checkout 001b8e1b`
2. `make start`
3. `make test-bot-farm` <- run this command a few times, usually doesn't occur immediately after a fresh `make reset` but once it does occur, it will occur somewhat-reliably during the test's first eth deposit.

**Expected behavior**
I expect it to not error

**Your Environment**

* Client version used: @connext/client@0.021
* Node version used: Whatever's built during `make start` on commit `001b8e1b`
* Chain used: ganache
* Browser Name and version: N/A
* Operating System and version (desktop or mobile): docker
* Link to your project: this

**Comment by bohendo** [comment]
I'm also regularly seeing the following:
```
[Nest] 66   - 08/29/2019, 10:32 AM   [ListenerService] protocolMessageEvent event fired from xpub6Dog9NB3dNByjbMoS64PPcrHVzGAWzHnUomNxLxE7CkiBB5mc3ERX6EGnW4Niec9YAh4jSwY1rdJ7xhVFTTQpU352xMs8AEZBPMQVKxs9bd, data: {"params":{"initiatorXpub":"xpub6Dog9NB3dNByjbMoS64PPcrHVzGAWzHnUomNxLxE7CkiBB5mc3ERX6EGnW4Niec9YAh4jSwY1rdJ7xhVFTTQpU352xMs8AEZBPMQVKxs9bd","responderXpub":"xpub6DwySHvzY65bu2WL2XZFbyiEs6ACpTUtZDPwmkj4nANASh2x9agQUDGsVkAvbhjTpzUTsFsQK98oAEKa6bQzLE56R48zQwWMdGn61iLv8xD","intermediaryXpub":"xpub6E3tjd9js7QMrBtYo7f157D7MwauL6MWdLzKekFaRBb3bvaQnUPjHKJcdNhiqSjhmwa6TcTjV1wSDTgvz52To2ZjhGMiQFbYie2N2LZpNx6","targetOutcome":"0x0000000000000000000000006f8c806687dafda1846f658d43b76f55f10f91270000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a402395fcdb6f31a07c566833e850ea37cde278500000000000000000000000000000000000000000000000000b1a2bc2ec50000","targetAppIdentityHash":"0x3b32fa7ebd2101b407871d8fdd3c6ef8d25ae986dda9df656c814b2f7af2132f"},"processID":"5851e950-ca48-11e9-8395-8bb08f7c23c4","protocol":"uninstall-virtual-app","seq":1,"toXpub":"xpub6E3tjd9js7QMrBtYo7f157D7MwauL6MWdLzKekFaRBb3bvaQnUPjHKJcdNhiqSjhmwa6TcTjV1wSDTgvz52To2ZjhGMiQFbYie2N2LZpNx6","customData":{"signature":{"recoveryParam":0,"r":"0x63c4c3bb6d916905142d29c39176a717f5a464c96a2ac5f9786efebe4f74127d","s":"0x503d0800a620fe21eb8922c1d97acb4740d40f52666d98893460de3c931e6aeb","v":27}}}
[Nest] 66   - 08/29/2019, 10:32 AM   [ListenerService] protocolMessageEvent event fired from xpub6DwySHvzY65bu2WL2XZFbyiEs6ACpTUtZDPwmkj4nANASh2x9agQUDGsVkAvbhjTpzUTsFsQK98oAEKa6bQzLE56R48zQwWMdGn61iLv8xD, data: {"params":{"initialState":{"coinTransfers":[{"amount":{"_hex":"0xb1a2bc2ec50000"},"to":"0x6f8c806687Dafda1846F658D43B76F55F10F9127"},{"amount":{"_hex":"0x00"},"to":"0xa402395FcDB6f31a07c566833E850eA37cDe2785"}]},"outcomeType":"SINGLE_ASSET_TWO_PARTY_COIN_TRANSFER","initiatorXpub":"xpub6DwySHvzY65bu2WL2XZFbyiEs6ACpTUtZDPwmkj4nANASh2x9agQUDGsVkAvbhjTpzUTsFsQK98oAEKa6bQzLE56R48zQwWMdGn61iLv8xD","responderXpub":"xpub6Dog9NB3dNByjbMoS64PPcrHVzGAWzHnUomNxLxE7CkiBB5mc3ERX6EGnW4Niec9YAh4jSwY1rdJ7xhVFTTQpU352xMs8AEZBPMQVKxs9bd","intermediaryXpub":"xpub6E3tjd9js7QMrBtYo7f157D7MwauL6MWdLzKekFaRBb3bvaQnUPjHKJcdNhiqSjhmwa6TcTjV1wSDTgvz52To2ZjhGMiQFbYie2N2LZpNx6","defaultTimeout":0,"appInterface":{"addr":"0x75c35C980C0d37ef46DF04d31A140b65503c0eEd","actionEncoding":null,"stateEncoding":"\n          tuple(\n            \n  tuple(address to, uint256 amount)[2]\n coinTransfers\n          )"},"initiatorBalanceDecrement":{"_hex":"0x00"},"responderBalanceDecrement":{"_hex":"0xb1a2bc2ec50000"},"tokenAddress":"0x0000000000000000000000000000000000000000"},"protocol":"install-virtual-app","processID":"57f3ead0-ca48-11e9-bfce-3be655c8c561","toXpub":"xpub6E3tjd9js7QMrBtYo7f157D7MwauL6MWdLzKekFaRBb3bvaQnUPjHKJcdNhiqSjhmwa6TcTjV1wSDTgvz52To2ZjhGMiQFbYie2N2LZpNx6","seq":1,"customData":{"signature":{"recoveryParam":1,"r":"0x1a0a08acf8a6394646c5c5083c3ce4b88ac6c4e100a374709c64e1143829b4f4","s":"0x7f9cead9cd925b96a41cdd0a0e9f92bb94d48cba5a600761610ebab0e7b2ff33","v":28},"signature2":"0x3b32fa7ebd2101b407871d8fdd3c6ef8d25ae986dda9df656c814b2f7af2132f","signature3":"0x0000000000000000000000006f8c806687dafda1846f658d43b76f55f10f91270000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a402395fcdb6f31a07c566833e850ea37cde278500000000000000000000000000000000000000000000000000b1a2bc2ec50000"}}
(node:66) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getAppInstance' of undefined
    at getUpdatedStateChannelAndAppInstanceObjectsForIntermediary (/root/node_modules/@counterfactual/node/src/protocol/uninstall-virtual-app.ts:774:76)
    at /root/node_modules/@counterfactual/node/src/protocol/uninstall-virtual-app.ts:204:15
    at Generator.next (<anonymous>)
    at resume (/root/node_modules/@counterfactual/node/dist/index.js:52:44)
    at /root/node_modules/@counterfactual/node/dist/index.js:51:121
    at new Promise (<anonymous>)
    at Object.i.(anonymous function) [as next] (/root/node_modules/@counterfactual/node/dist/index.js:51:63)
    at InstructionExecutor.runProtocol (/root/node_modules/@counterfactual/node/src/machine/instruction-executor.ts:148:33)
    at InstructionExecutor.runProtocolWithMessage (/root/node_modules/@counterfactual/node/src/machine/instruction-executor.ts:99:17)
    at executeFunctionWithinQueues (/root/node_modules/@counterfactual/node/src/message-handling/handle-protocol-message.ts:56:58)
```
The above error occurs while attempting to make a p2p eth transfer. This appears to be the vitual-app version of the above where we're attempting to uninstall a virtual app that isn't installed.

**Comment by bohendo** [comment]
Neither of the above errors have been observed while attempting to deposit or transfer tokens, only eth.

**Comment by bohendo** [comment]
Hint: I noticed this in my bot test logs:
```
########################################
Depositing eth into sender bot 1
Payment bot launched:
 - mnemonic: robust grass anxiety betray reopen festival window trumpet gap satisfy position abuse
 - ethProviderUrl: http://172.17.0.1:8545
 - nodeUrl: nats://172.17.0.1:4222
 - publicIdentifier: xpub6F7jeDP6ovkfkCRmW3domuV3XsfWrE5QmeiMDdwGsZuyZmvCapLDbCowxBa456iPsHEnXF2oyGxZxxFMtSoELNgScm5eTcrQekN6c18Wwbb
 - multisigAddress: 0xFA0462A994b84BBF2D0DE6159abf7167B5492287
 - User freeBalanceAddress: 0x0EA6F0fC013A68C1832bcfa90CA1d376D151a721
 - Node freeBalance address: 0xF80fd6F5eF91230805508bB28d75248024E50F6F
Depositing 0.05 of asset 0x0000000000000000000000000000000000000000
^CShutting down recipient bots: f88b18a881bc
f88b18a881bc
Shutting down recipient bots: 
nvmd none are running
```
Looks like a ctrl-c (`^C`) during an eth deposit might have triggered this.

**Comment by ArjunBhuptani** [comment]
Closing, can reopen if it pops up again
