### ISSUE TITLE
Error: Call to getStateChannel failed when searching for multisig address: <unused-address>

### ISSUE THREAD

**Issue by bohendo** [ConnextProject/indra#330]
**Describe the bug**

While redeeming a link payment (both generate & redeem via card UI), the redemption hangs and the hub prints the following:

```
[Nest] 1   - 09/19/2019, 2:30 PM   [TransferMessaging] Got resolve link request with data: {
  "amount": "[object Object]",
  "assetId": "0xFab46E002BbF0b4509813474841E0716E6730136",
  "paymentId": "0xb46c933e1aa44dfeae63eaf2a206ef0d8a20b081c8e015490b02052e5ae25534",
  "preImage": "0x8039a731b6f2e6e1dcd6050ca8efbdf0bf2c62e631ad6ad2ee119d054f19f84f",
  "id": "6e89b1ee-b439-4f3a-b7ad-6a20ee48ed32"
}
[Nest] 1   - 09/19/2019, 2:30 PM   [TransferService] Resolving linked transfer with userPubId: xpub6EnwoKsEWFeQfkp1pcjQ1xFym7G38VpYuNQ7wv3758cEnF7xYXwhPMz5ucnoxxdiUegWgStbtEqQdXF5RMhk3TTwSaFmjQSDwm5LLTvQsFd, paymentId: 0xb46c933e1aa44dfeae63eaf2a206ef0d8a20b081c8e015490b02052e5ae25534, preImage: 0x8039a731b6f2e6e1dcd6050ca8efbdf0bf2c62e631ad6ad2ee119d054f19f84f, amount: 1000000000000000000, assetId: 0xFab46E002BbF0b4509813474841E0716E6730136
[Nest] 1   - 09/19/2019, 2:30 PM   [TransferService] Found linked transfer in our database, attempting to resolve...
[Nest] 1   - 09/19/2019, 2:30 PM   [ChannelService] xpub6EnwoKsEWFeQfkp1pcjQ1xFym7G38VpYuNQ7wv3758cEnF7xYXwhPMz5ucnoxxdiUegWgStbtEqQdXF5RMhk3TTwSaFmjQSDwm5LLTvQsFd already has collateral of 10000000000000000000 for asset 0xFab46E002BbF0b4509813474841E0716E6730136
(node:1) UnhandledPromiseRejectionWarning: Error: Call to getStateChannel failed when searching for multisig address: 0xf87daBCf4865Bf2783f43077f554945965907b5a. This probably means that the StateChannel does not exist yet.
    at Store.getStateChannel (/root/node_modules/@counterfactual/node/dist/index.js:3575:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

Note that the sender's multisig is at `0xBD0F0408F2Bb231182dAB1cB1F0dd0b9254E179d` and the recipients is at `0x7846DAac31fBa80b244Ec1A419d15F9D83acF990` and neither match the one that the hub things doesn't exist (so it probably doesn't exist, idk where it came from)

The `amont: [object Object]` is also concerning but other places the amount is logged look good so maybe only a problem in the one place that was logged?

**To Reproduce**
1. Go to staging.indra.connext.network in two browsers
2. Deposit into both (maybe only necessary to deposit into sender?) and generate a link from one
3. Try to redeem link in the other. Notice it never completes
4. View hub logs to see above error

Potentially confounding issue: this was originally noticed using an old channel that's been around since previous versions. Maybe it got corrupted somehow?

TODO: test locally

**Expected behavior**
link payments should work.

**Comment by bohendo** [comment]
Got same error during p2p transfers:
```
Uncaught (in promise) Error: Call to getStateChannel failed when searching for multisig address: 0xf87daBCf4865Bf2783f43077f554945965907b5a. This probably means that the StateChannel does not exist yet.
```

**Comment by bohendo** [comment]
Both link transfer and sends worked with a fresh card so let's credit this bug to out-of-date/corrupt data in localStorage. We'll open a new issue w better repro details if this problem re-emerges
