### ISSUE TITLE
[client] restoreState does not exist (or work)

### ISSUE THREAD

**Issue by bohendo** [ConnextProject/indra#424]
## Describe the bug
Noticed this in the tip bot.

```
src/channel/channel.service.ts:54:25 - error TS2339: Property 'restoreState' does not exist on type 'ConnextInternal'.

54           await channel.restoreState(this.config.wallet.mnemonic);
                           ~~~~~~~~~~~~
```

## To Reproduce
1. Try to call `channel.restoreState(this.config.wallet.mnemonic);`
2. See error

Using `@connext/client@0.2.0`

Some other weird stuff: we're returning a `ConnextInternal` from the `connect()` method so it seems like the abstract `ConnextChannel` class isn't actually being used anywhere except as an abstract class implemented by `ConnextInternal`.. in which case, shouldn't the abstract class just be an interface instead?

Kind of a workaround: use `channel.restoreStateFromNode()` instead.

Except this also doesn't work. It complete w/out issue but the state seems to be incorrectly restored because trying to redeem a payment afterwards fails. Example logs:

```
Redeeming payment: {"sender":{"id":2,"twitterId":"259539164","balance":"0.00"},"paymentId":"0x6124fc3dbeb4dab6b4f9c7a310b4497dee32cb4ed3732c7e619286fe9e3d06ec","secret":"0xd5948ab0c2d3227bb9687f280b26868b63fa6fad1144c8be061393f0b8086aa1","amount":"0.1","status":"PENDING","id":1}
We've been collateralized with 9.75, need 0.1
WARNING: PROPOSE_INSTALL_VIRTUAL is deprecated. Replace usage with PROPOSE_INSTALL.
WARNING: PROPOSE_INSTALL_VIRTUAL is deprecated. Replace usage with PROPOSE_INSTALL.
error: [NodeApiClient] Failed to execute callback while lock is held
error: [NodeApiClient] Error: No proposed AppInstance exists for the given appInstanceId: 0x5db753573ebf3b9440ddf3571c60fc4febdc833d728e1a3b1575dc791c90ae54
(node:163) UnhandledPromiseRejectionWarning: Error: No proposed AppInstance exists for the given appInstanceId: 0x5db753573ebf3b9440ddf3571c60fc4febdc833d728e1a3b1575dc791c90ae54
    at Store.getAppInstanceProposal (/root/node_modules/@counterfactual/node/dist/index.js:3603:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by bohendo** [comment]
Update: I think the connext client version I used was out of date

**Comment by bohendo** [comment]
Bot state before restore:
```
{
  "INDRA_CLIENT_CF_CORE:EXTENDED_PRIVATE_KEY": "xprv9s21ZrQH143K2rsSeRAo1PChNfaTQTgKBzKAddFFRADXDHcjzrA9oN4h92Ck2kjV6JNdjdDxwvGncsfKPpGa2CscSPa8k5Y7LMc9GnEYbdZ",
  "INDRA_CLIENT_CF_CORE:store/xpub6DXwZMmWUq4bRZ3LtaBYwu47XV4Td19pnngok2Y7DnRzcCJSKCmD1AcLJDbZZf5dzZpvHqYzmRaKf7Gd2MV9qDvWwwN7VpBPNXQCZCbfyoK/channel/0xFd7AaC36F74c6Fb4791191bE8c152d2A68a3163c": "{\"multisigAddress\":\"0xFd7AaC36F74c6Fb4791191bE8c152d2A68a3163c\",\"userNeuteredExtendedKeys\":[\"xpub6E3tjd9js7QMrBtYo7f157D7MwauL6MWdLzKekFaRBb3bvaQnUPjHKJcdNhiqSjhmwa6TcTjV1wSDTgvz52To2ZjhGMiQFbYie2N2LZpNx6\",\"xpub6DXwZMmWUq4bRZ3LtaBYwu47XV4Td19pnngok2Y7DnRzcCJSKCmD1AcLJDbZZf5dzZpvHqYzmRaKf7Gd2MV9qDvWwwN7VpBPNXQCZCbfyoK\"],\"proposedAppInstances\":[],\"appInstances\":[],\"freeBalanceAppInstance\":{\"participants\":[\"0xd6e78115B145E6A988159Cc80483E7e6Bcfa12B0\",\"0xF80fd6F5eF91230805508bB28d75248024E50F6F\"],\"defaultTimeout\":172800,\"appInterface\":{\"addr\":\"0x8f0483125FCb9aaAEFA9209D8E9d7b9C8B9Fb90F\",\"stateEncoding\":\"\\n  tuple(\\n    address[] tokenAddresses,\\n    tuple(\\n      address to,\\n      uint256 amount\\n    )[][] balances,\\n    bytes32[] activeApps\\n  )\\n\"},\"isVirtualApp\":false,\"appSeqNo\":0,\"latestState\":{\"activeApps\":[],\"tokenAddresses\":[\"0x0000000000000000000000000000000000000000\"],\"balances\":[[{\"to\":\"0xd6e78115B145E6A988159Cc80483E7e6Bcfa12B0\",\"amount\":{\"_hex\":\"0xb1a2bc2ec50000\"}},{\"to\":\"0xF80fd6F5eF91230805508bB28d75248024E50F6F\",\"amount\":{\"_hex\":\"0x00\"}}]]},\"latestVersionNumber\":4,\"latestTimeout\":172800,\"outcomeType\":\"MULTI_ASSET_MULTI_PARTY_COIN_TRANSFER\",\"identityHash\":\"0xa39ce030ccff21ba4cc1ac7a84634dc3b13eb8d8a7670d65eae20729a9bc4e23\"},\"monotonicNumProposedApps\":1,\"singleAssetTwoPartyIntermediaryAgreements\":[],\"createdAt\":1570632006590}",
  "INDRA_CLIENT_CF_CORE:store/xpub6DXwZMmWUq4bRZ3LtaBYwu47XV4Td19pnngok2Y7DnRzcCJSKCmD1AcLJDbZZf5dzZpvHqYzmRaKf7Gd2MV9qDvWwwN7VpBPNXQCZCbfyoK/allCommitments/0x9518ddbed90c905584d4e5bb25ee36268eb3d0bbc64c3f1f380261b3498e387e": "[\"install\",\"0xbcbd925d6c9ecba5d6b3481deb8069694e67e1d6a306561c401bc0b8eb3e18b7\",{\"to\":\"0xFd7AaC36F74c6Fb4791191bE8c152d2A68a3163c\",\"value\":0,\"data\":\"0x58cb5e5a000000000000000000000000f12b5dd4ead5f743c6baa640b0216200e89b60da000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000001e000000000000000000000000000000000000000000000000000000000000001046858b1540000000000000000000000008cdaf0cd259887258bc13a92c0a6da92698644c0a39ce030ccff21ba4cc1ac7a84634dc3b13eb8d8a7670d65eae20729a9bc4e23bcbd925d6c9ecba5d6b3481deb8069694e67e1d6a306561c401bc0b8eb3e18b700000000000000000000000030753e4a8aad7f8597332e813735def5dd39502800000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000040ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000041f662f8dc5e2ca1ab2448932f6688f7438b7fdb254fb58b430e0961f5a567d0e6628d1da19e507026c71fead4834bf28b4ac6161efcce91b196fc9527c700a4ab1c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000041550740ef9ef2ccbb5a2976d8a42f18237dcb5c6afba925650d9190162348c6b66aff3241df5bcc6124009e1a9d1654ebde1f940e73eff853bf71575ed82babf51c00000000000000000000000000000000000000000000000000000000000000\"}]",
  "INDRA_CLIENT_CF_CORE:store/xpub6DXwZMmWUq4bRZ3LtaBYwu47XV4Td19pnngok2Y7DnRzcCJSKCmD1AcLJDbZZf5dzZpvHqYzmRaKf7Gd2MV9qDvWwwN7VpBPNXQCZCbfyoK/allCommitments/0x274d63ff2c1c5277c7a3b9f07df40f66d7564ad526b1ab2e4d5fbb7c7ae007c0": "[\"update\",\"0xa39ce030ccff21ba4cc1ac7a84634dc3b13eb8d8a7670d65eae20729a9bc4e23\",{\"to\":\"0x8CdaF0CD259887258Bc13a92C0a6dA92698644C0\",\"value\":0,\"data\":\"0x15821a0600000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000008f0483125fcb9aaaefa9209d8e9d7b9c8b9fb90f000000000000000000000000000000000000000000000000000000000002a3000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000d6e78115b145e6a988159cc80483e7e6bcfa12b0000000000000000000000000f80fd6f5ef91230805508bb28d75248024e50f6fc8acf3c5687d17f8bb6608d7c39ec3a35015bb571c9318f54a04c49faee412650000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000002a30000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000004195f475fc94e5664b3d1e70a327bfdf685c267593387e5c0f91a39d9ac21f69ed5c64b598c5fd2fb93a5b3032e77877ca4f8222c715d7aa39dbd47d7fffcdf95b1b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000410dcedb7e3fb3a79daea74cc5bf8bec2fa5dff19987edca2e3d0df79ab93b0b3d0c9b05a7b352ff59d6e47ba84f2b84a307c413ba243ed39562cff8ff5c6f5a361b00000000000000000000000000000000000000000000000000000000000000\"}]",
  "INDRA_CLIENT_CF_CORE:store/xpub6DXwZMmWUq4bRZ3LtaBYwu47XV4Td19pnngok2Y7DnRzcCJSKCmD1AcLJDbZZf5dzZpvHqYzmRaKf7Gd2MV9qDvWwwN7VpBPNXQCZCbfyoK/allCommitments/0x3faf82be9744cc9cfcb564d13cfe0b9465f52c528897412f1971d923ce85ad12": "[\"uninstall\",\"0xbcbd925d6c9ecba5d6b3481deb8069694e67e1d6a306561c401bc0b8eb3e18b7\",{\"to\":\"0x8CdaF0CD259887258Bc13a92C0a6dA92698644C0\",\"value\":0,\"data\":\"0x15821a0600000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000008f0483125fcb9aaaefa9209d8e9d7b9c8b9fb90f000000000000000000000000000000000000000000000000000000000002a3000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000d6e78115b145e6a988159cc80483e7e6bcfa12b0000000000000000000000000f80fd6f5ef91230805508bb28d75248024e50f6f1cccfb9b9cbd2c2f95cc6b94bdffa9051bb3fd226f77b8f1048c0b83e0b9d6240000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000002a30000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000418477632c9ce46a5c409bdd231c95ca87b1b1f8b0603e1402512af6df0b4640393ba72f6ef0285dc9efb41bda3502d7c2e0ae03de3b0f92291ddb902d8262120f1b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000041afeca7f60e693ef6fad4260c7aef9c7e18dc20132b12ec7252239930922503b87312cec2836271e47a75eb35cac8fc5bec7fff4aa3f55867b981425bed5647001b00000000000000000000000000000000000000000000000000000000000000\"}]"
}
```
Bot state after:
```
{
  "INDRA_CLIENT_CF_CORE:EXTENDED_PRIVATE_KEY": "xprv9s21ZrQH143K2rsSeRAo1PChNfaTQTgKBzKAddFFRADXDHcjzrA9oN4h92Ck2kjV6JNdjdDxwvGncsfKPpGa2CscSPa8k5Y7LMc9GnEYbdZ",
  "INDRA_CLIENT_CF_CORE:store/xpub6DXwZMmWUq4bRZ3LtaBYwu47XV4Td19pnngok2Y7DnRzcCJSKCmD1AcLJDbZZf5dzZpvHqYzmRaKf7Gd2MV9qDvWwwN7VpBPNXQCZCbfyoK/channel/0xFd7AaC36F74c6Fb4791191bE8c152d2A68a3163c": "{\"multisigAddress\":\"0xFd7AaC36F74c6Fb4791191bE8c152d2A68a3163c\",\"userNeuteredExtendedKeys\":[\"xpub6E3tjd9js7QMrBtYo7f157D7MwauL6MWdLzKekFaRBb3bvaQnUPjHKJcdNhiqSjhmwa6TcTjV1wSDTgvz52To2ZjhGMiQFbYie2N2LZpNx6\",\"xpub6DXwZMmWUq4bRZ3LtaBYwu47XV4Td19pnngok2Y7DnRzcCJSKCmD1AcLJDbZZf5dzZpvHqYzmRaKf7Gd2MV9qDvWwwN7VpBPNXQCZCbfyoK\"],\"proposedAppInstances\":[],\"appInstances\":[],\"freeBalanceAppInstance\":{\"participants\":[\"0xd6e78115B145E6A988159Cc80483E7e6Bcfa12B0\",\"0xF80fd6F5eF91230805508bB28d75248024E50F6F\"],\"defaultTimeout\":172800,\"appInterface\":{\"addr\":\"0x8f0483125FCb9aaAEFA9209D8E9d7b9C8B9Fb90F\",\"stateEncoding\":\"\\n  tuple(\\n    address[] tokenAddresses,\\n    tuple(\\n      address to,\\n      uint256 amount\\n    )[][] balances,\\n    bytes32[] activeApps\\n  )\\n\"},\"isVirtualApp\":false,\"appSeqNo\":0,\"latestState\":{\"activeApps\":[],\"tokenAddresses\":[\"0x0000000000000000000000000000000000000000\"],\"balances\":[[{\"to\":\"0xd6e78115B145E6A988159Cc80483E7e6Bcfa12B0\",\"amount\":{\"_hex\":\"0xb1a2bc2ec50000\"}},{\"to\":\"0xF80fd6F5eF91230805508bB28d75248024E50F6F\",\"amount\":{\"_hex\":\"0x00\"}}]]},\"latestVersionNumber\":4,\"latestTimeout\":172800,\"outcomeType\":\"MULTI_ASSET_MULTI_PARTY_COIN_TRANSFER\",\"identityHash\":\"0xa39ce030ccff21ba4cc1ac7a84634dc3b13eb8d8a7670d65eae20729a9bc4e23\"},\"monotonicNumProposedApps\":1,\"singleAssetTwoPartyIntermediaryAgreements\":[],\"createdAt\":1570632006513}"
}
```

**Comment by rhlsthrm** [comment]
This should be fine with your updated logging. Did you verify that the redemption works?

**Comment by LayneHaber** [comment]
I can add an e2e test for this on the card, will link with a PR later today

**Comment by LayneHaber** [comment]
whoops looks like there already is one [here](https://github.com/ConnextProject/indra/blob/4f980bf56a2d52fe70256d776588c4917292cee1/cypress/tests/index.js#L85)

verified manually that you could recover things, so closing this
