### ISSUE TITLE
[test-runner] NatsError: Stale Connection

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#812]
**Describe the bug**
[This](https://github.com/ConnextProject/indra/blob/8b675de2682ed610549d1a61be2eb03aa8b2633a/modules/test-runner/src/transfer/asyncTransferOffline.test.ts#L299) test is failing when running in the full suite with a `NatsError: Stale Connection` but passes individually.

**Comment by bohendo** [comment]
Notice that nats-ts has the [connection option](https://github.com/nats-io/nats.ts#connect-options) `maxPingOut` (default=2) that sets "Max number of pings the client will allow unanswered before raising a stale connection error"

I tried setting this to 1000000 like below in `messaging/src/nats.ts`:
```

  async connect(): Promise<void> {
    const messagingUrl = this.config.messagingUrl;
    const config = this.config as nats.NatsConnectionOptions;
    config.servers = typeof messagingUrl === `string` ? [messagingUrl] : messagingUrl;
    config.payload = nats.Payload.JSON;
    // NOTE: high maxPingOut (default=2) to prevent errors while time-travelling during tests
    this.connection = await nats.connect({ ...config, maxPingOut: 1000000 });
    this.log.debug(`Connected!`);
  }
```
But this didn't fix it :(

**Comment by bohendo** [comment]
When did this error start popping up? I assume when we added the ability to time-travel through the offline tests?

**Comment by LayneHaber** [comment]
Yeah, came up when we started fast forwarding. Originally I saw it only in the async transfer test, but once I saw it with having the test skipped.

I also saw something when I was looking into it that it happens when the connection hasn't been used for 6min

**Comment by bohendo** [comment]
```
[{"amount":"1000000000000000000","to":"0xAFead1bbfa4Ba0523a0F317607c80DA9A0d40587"},{"amount":"0","to":"0xF80fd6F5eF91230805508bB28d75248024E50F6F"}],"linkedHash":"0x468a7dedd028c1951b7d35f9358cbd99146a7f5196d3e8152a644b2ea0157564","paymentId":"0xfd6f483546d83d6433462e0c8a1da548c6727aa6130296cecc76e686310c4407","preImage":"0x0000000000000000000000000000000000000000000000000000000000000000"}}
[LockService] Failed to execute callback while lock is held: IO_SEND_AND_WAIT timed out after 90s waiting for counterparty reply in propose +46299ms
Error: IO_SEND_AND_WAIT timed out after 90s waiting for counterparty reply in propose
    at /root/modules/cf-core/src/node.ts:219:17
    at ProtocolRunner.runProtocol (/root/modules/cf-core/src/machine/protocol-runner.ts:157:27)
    at ProposeInstallController.executeMethodImplementation (/root/modules/cf-core/src/methods/app-instance/propose-install/controller.ts:124:5)
[LockService] Releasing lock for 0xb1E220A68C2615f43f885a950E5A8005dDF0b62A with secret df2ec091248566122918f1e18c5844cd
[LockService] Failed to release the lock due to expired ttl: LockError: Unable to fully release the lock on resource "0xb1E220A68C2615f43f885a950E5A8005dDF0b62A".; 
[LockService] No return value found from task with lockName: 0xb1E220A68C2615f43f885a950E5A8005dDF0b62A, and failed to release due to expired ttl: Unable to fully release the lock on resource "0xb1E220A68C2615f43f885a950E5A8005dDF0b62A". +1ms
LockError: Unable to fully release the lock on resource "0xb1E220A68C2615f43f885a950E5A8005dDF0b62A".
    at loop (/root/node_modules/redlock/redlock.js:265:18)
    at tryCatcher (/root/node_modules/standard-as-callback/built/utils.js:11:23)
    at /root/node_modules/standard-as-callback/built/index.js:19:49
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```
see this in node logs

**Comment by rhlsthrm** [comment]
This error happens when the client goes offline mid-protocol.
